import type { PalaceName } from "../types/chart";

/**
 * Penjelasan tiap bintang menurut palace tempatnya berada.
 *
 * Kunci luar  : nama bintang (English) — sama persis dengan STAR_ZH di lib/calculateChart.ts
 * Kunci dalam : PalaceName (Life, Siblings, ... Parents)
 *
 * Cakupan: 14 bintang utama + 16 bintang bantu (aux). Bintang misc belum diisi.
 *
 * Catatan tafsir: teks di bawah adalah makna DASAR bintang di palace itu, belum
 * memperhitungkan terang-gelap (廟旺得平陷), Si Hua, atau bintang pendamping.
 * Aturan praktis yang tetap berlaku saat membaca:
 *   - terang (1-2) menguatkan sisi positif, gelap (4-5) menonjolkan sisi rapuhnya;
 *   - Hua Lu/Quan/Ke memperbaiki, Hua Ji membalik jadi beban;
 *   - Sha star (Qing Yang, Tuo Luo, Huo, Ling, Kong, Jie) menambah gesekan.
 */
export type StarMeanings = Record<string, Partial<Record<PalaceName, string>>>;

export const STAR_MEANINGS: StarMeanings = {
  // ── 14 Bintang Utama ────────────────────────────────────────────────────
  "Zi Wei": {
    Life: "Berwibawa, ingin dihormati, dan nyaman memegang kendali. Punya standar tinggi dan gengsi yang kuat; bila tanpa bintang pendukung (Zuo Fu, You Bi, Kui Yue) mudah jadi pemimpin tanpa pasukan — banyak maunya, sedikit yang membantu.",
    Siblings: "Ada saudara atau rekan yang posisinya lebih tinggi, lebih mapan, atau dominan. Hubungan cenderung hormat tetapi berjarak; Anda mudah jadi pihak yang mengalah pada wibawa mereka.",
    Spouse: "Pasangan berkarakter kuat, berkelas, dan ingin dihormati. Pernikahan berjalan baik bila Anda memberi ruang bagi harga dirinya; bila keduanya sama-sama ingin memimpin, rumah tangga jadi arena adu gengsi.",
    Children: "Anak berwatak kuat, mandiri, dan tidak mudah diperintah. Anda mendidik dengan wibawa; anak berpotensi berprestasi tetapi jumlahnya cenderung sedikit dan lahir belakangan.",
    Wealth: "Uang datang dari posisi, jabatan, atau nama besar — bukan dari kerja kasar. Gaya belanja mengikuti gengsi, sehingga penghasilan besar sering diimbangi pengeluaran besar untuk penampilan.",
    Health: "Fisik dasarnya kuat dan daya tahan baik. Keluhan biasanya di lambung dan pencernaan, dipicu tekanan tanggung jawab dan pola makan tak teratur.",
    Travel: "Di luar rumah Anda dipandang dan mudah dapat tempat. Perantauan justru mengangkat derajat; banyak pertolongan datang dari orang berkedudukan.",
    Friends: "Dikelilingi orang berpengaruh, tetapi mereka cenderung menuntut dan tidak mudah diatur. Bawahan bisa lebih menonjol dari Anda bila tidak dikelola.",
    Career: "Cocok di jalur struktural: pemerintahan, korporasi besar, atau posisi pimpinan. Karier naik lewat jabatan dan kepercayaan, bukan lewat teknis.",
    Property: "Punya potensi rumah atau properti bernilai bagus, sering di lokasi terpandang. Suka menata rumah agar terlihat berkelas.",
    Happiness: "Batin menuntut kualitas dan kehormatan; sulit menikmati sesuatu yang dirasa murahan. Bisa menikmati hidup tetapi gengsi kerap menahan rasa cukup.",
    Parents: "Orang tua atau atasan berwibawa dan berpengaruh terhadap arah hidup Anda. Anda hormat kepada mereka namun sering merasa berada di bawah bayang-bayangnya.",
  },
  "Tian Ji": {
    Life: "Cerdas, cepat menangkap pola, penuh siasat, dan gemar berpikir. Kelemahannya gelisah — banyak ide, sering ganti arah, dan mudah lelah oleh pikiran sendiri.",
    Siblings: "Saudara pintar dan banyak akal, tetapi hubungan naik-turun dan mudah berubah kedekatannya. Sering saling bantu lewat nasihat, bukan materi.",
    Spouse: "Pasangan cerdas, cerewet pikirannya, dan suka menganalisis. Perjodohan sering lewat kenalan atau perantara; hubungan perlu obrolan agar tidak dingin.",
    Children: "Anak cerdas, lincah, dan banyak tanya. Cocok didorong ke jalur akademik atau keterampilan berpikir; kesehatannya perlu diperhatikan saat kecil.",
    Wealth: "Uang mengalir dari otak: perencanaan, perantara, konsultasi, atau bidang teknis. Pemasukannya bergerak naik-turun, tidak cocok dengan cara mengumpulkan yang statis.",
    Health: "Titik lemahnya saraf, tidur, dan hati (liver). Keluhan sering muncul karena terlalu banyak berpikir dan kurang istirahat.",
    Travel: "Banyak bergerak dan berpindah; peluang justru muncul saat berpindah tempat. Perjalanan sering mendadak dan berubah rencana.",
    Friends: "Teman datang-pergi silih berganti, banyak yang pintar tapi sedikit yang bertahan lama. Relasi lebih bersifat tukar informasi.",
    Career: "Cocok di perencanaan, analisis, mesin, teknologi, pendidikan, atau konsultan. Pekerjaan yang menuntut rutinitas monoton membuat Anda cepat bosan.",
    Property: "Sering pindah rumah atau merenovasi. Properti tidak dipegang lama; ada kecenderungan jual-beli atau kontrak berganti.",
    Happiness: "Batin sibuk dan jarang benar-benar diam. Ketenangan datang dari belajar, membaca, atau menekuni hal spiritual dan filsafat.",
    Parents: "Orang tua bijak dan suka menasihati. Hubungan hangat lewat diskusi, tetapi mudah berubah suasana bila keduanya sama-sama keras kepala.",
  },
  "Tai Yang": {
    Life: "Terbuka, murah hati, semangat memberi, dan senang tampil di depan. Cenderung sibuk mengurusi orang lain sampai lupa diri sendiri; bila redup, lelah dan merasa kurang dihargai.",
    Siblings: "Ada saudara laki-laki yang menonjol atau menjadi tulang punggung. Anda banyak berkorban untuk saudara.",
    Spouse: "Bagi wanita menunjuk suami yang terbuka dan bertanggung jawab; bagi pria, pasangan yang aktif di luar rumah. Bila Tai Yang gelap, pasangan sibuk dan hubungan terasa kurang hangat.",
    Children: "Anak laki-laki menonjol, aktif, dan berhati besar. Anda memberi kebebasan dan dukungan penuh pada anak.",
    Wealth: "Uang diperoleh sambil memberi manfaat kepada orang banyak — nama baik dulu, uang menyusul. Boros untuk membantu orang lain.",
    Health: "Perhatikan mata, kepala, tekanan darah, dan jantung. Kelelahan datang dari terlalu banyak mengurusi urusan orang.",
    Travel: "Bersinar di luar rumah dan luar kota; nama Anda dikenal justru saat merantau. Banyak kegiatan sosial di luar.",
    Friends: "Banyak teman dan luas pergaulan, sering menjadi tempat orang meminta bantuan. Balasan yang diterima biasanya tidak sepadan.",
    Career: "Cocok di bidang publik: pendidikan, pemerintahan, penyiaran, hukum, atau organisasi. Karier terangnya bergantung pada terang-gelapnya bintang.",
    Property: "Rumah terang, menghadap terbuka, dan ramai dikunjungi. Properti sering dipakai bersama keluarga besar.",
    Happiness: "Puas ketika bisa berguna bagi orang lain. Bila redup, muncul rasa lelah batin karena merasa memberi tanpa dihargai.",
    Parents: "Hubungan dengan ayah menonjol — bisa sangat dekat atau justru berjarak bila bintangnya gelap. Atasan cenderung terbuka dan mendukung.",
  },
  "Wu Qu": {
    Life: "Tegas, disiplin, berorientasi hasil, dan kuat soal uang. Bicara lugas sampai terkesan kaku; kurang luwes dalam urusan perasaan.",
    Siblings: "Saudara berwatak keras dan mandiri secara finansial. Hubungan lebih ke urusan praktis daripada kedekatan emosi.",
    Spouse: "Pasangan mandiri, hemat, dan tegas. Hubungan aman secara materi tetapi kering secara ungkapan; pernikahan sebaiknya tidak terlalu muda.",
    Children: "Anak berwatak keras, mandiri, dan tidak manja. Pola asuh Anda disiplin; jumlah anak cenderung sedikit.",
    Wealth: "Bintang keuangan yang paling murni: pandai mencari, mengelola, dan menyimpan uang. Cocok di keuangan, logam, atau usaha nyata yang terukur.",
    Health: "Perhatikan paru-paru, saluran napas, hidung, dan gigi. Ada kecenderungan luka atau tindakan operasi bila bertemu sha star.",
    Travel: "Rezeki dicari dengan bergerak dan berjuang di luar. Perantauan berhasil lewat kerja keras, bukan koneksi.",
    Friends: "Teman seadanya tetapi solid dan terkait kepentingan usaha. Mudah bersinggungan soal uang bila batasnya tidak jelas.",
    Career: "Cocok di keuangan, perbankan, akuntansi, manufaktur, militer, atau bisnis sendiri. Kuat pada eksekusi, bukan basa-basi.",
    Property: "Mampu mengumpulkan properti dari usaha sendiri. Rumah dipilih karena nilai dan fungsi, bukan keindahan.",
    Happiness: "Tenang bila keuangan aman. Sulit santai; istirahat pun sering dipakai memikirkan pekerjaan.",
    Parents: "Orang tua tegas dan berdisiplin, hubungan kurang manis tetapi bertanggung jawab. Atasan menuntut hasil nyata.",
  },
  "Tian Tong": {
    Life: "Ramah, lembut, mudah bergaul, dan pandai menikmati hidup. Kelemahannya kurang tahan tekanan dan cenderung menunda; berkembang justru setelah melewati kesulitan.",
    Siblings: "Saudara akrab dan menyenangkan, hubungan hangat tanpa banyak konflik. Namun bantuan nyata dari mereka terbatas.",
    Spouse: "Pasangan lembut, penyayang, dan awet muda. Rumah tangga adem, tetapi bila terlalu manja hubungan jadi kurang berkembang.",
    Children: "Anak manis, penurut, dan dekat dengan Anda. Hubungan orang tua-anak hangat dan minim konflik.",
    Wealth: "Rezeki mengalir tanpa perjuangan berlebihan, sering dari kenyamanan hidup atau bantuan orang. Kurang gigih menumpuk kekayaan besar.",
    Health: "Perhatikan berat badan, ginjal, saluran kemih, dan kadar gula. Kurang gerak menjadi penyebab utama.",
    Travel: "Di luar rumah banyak yang menolong dan hidup terasa nyaman. Perjalanan lebih ke rekreasi daripada perjuangan.",
    Friends: "Banyak teman yang menyenangkan dan mudah akrab. Sedikit yang bisa diandalkan saat susah.",
    Career: "Cocok di bidang layanan, hiburan, makanan-minuman, kesehatan, atau pekerjaan bersuasana santai. Kurang cocok di posisi bertekanan tinggi.",
    Property: "Rumah nyaman dan menjadi tempat berkumpul. Cenderung dapat properti dari warisan atau bantuan keluarga.",
    Happiness: "Bintang keberuntungan batin — pandai bersenang-senang dan cepat memaafkan diri. Ini letak terbaik Tian Tong.",
    Parents: "Orang tua penyayang dan tidak menekan. Atasan bersikap baik dan mudah diajak bicara.",
  },
  "Lian Zhen": {
    Life: "Punya prinsip, tajam, dan berkarisma dengan daya pikat sosial yang kuat. Emosinya ekstrem: bisa sangat berdisiplin, bisa sangat memberontak.",
    Siblings: "Hubungan dengan saudara pasang-surut, ada persaingan diam-diam. Bisa akrab dalam pergaulan tetapi mudah tersinggung.",
    Spouse: "Pasangan menarik dan berkarakter kuat. Hubungan penuh warna namun rawan cemburu dan tarik-menarik emosi; perlu komitmen jelas.",
    Children: "Anak cerdas, tampan atau cantik, tetapi keras kepala. Butuh pendekatan bicara, bukan perintah.",
    Wealth: "Uang datang dari relasi, negosiasi, dan kemampuan sosial. Rawan tersangkut urusan hukum atau perjanjian bila ada sha star.",
    Health: "Perhatikan darah, jantung, dan sistem reproduksi. Emosi yang tertahan mudah berubah jadi keluhan fisik.",
    Travel: "Pergaulan luas di luar rumah; peluang sekaligus godaan datang dari sana. Perlu hati-hati dalam pergaulan bebas.",
    Friends: "Teman beragam latar belakang, ada yang membantu dan ada yang menyeret. Pilih lingkaran dengan cermat.",
    Career: "Cocok di bidang hukum, humas, politik, hiburan, penjualan, atau apa pun yang menuntut negosiasi. Kuat saat harus berhadapan dengan orang.",
    Property: "Rumah tertata rapi dan berselera. Ada kemungkinan urusan sengketa atau surat-surat properti bila bertemu sha star.",
    Happiness: "Batin ramai, mudah tergoda hiburan dan hal-hal indah. Ketenangan datang bila punya pegangan prinsip.",
    Parents: "Hubungan dengan orang tua kuat namun mudah bergesekan soal aturan. Atasan berkarakter tegas dan menuntut loyalitas.",
  },
  "Tian Fu": {
    Life: "Tenang, stabil, hati-hati, dan pandai menyimpan. Punya wibawa lembut dan rasa aman yang tinggi; kelemahannya konservatif dan kurang berani mengambil risiko.",
    Siblings: "Saudara mapan dan dapat diandalkan. Hubungan tenang, saling menjaga, jarang ribut.",
    Spouse: "Pasangan penyabar, bertanggung jawab, dan mapan secara materi. Pernikahan stabil dan cenderung awet.",
    Children: "Anak berperilaku baik, tenang, dan tahu aturan. Hubungan harmonis dan saling menghormati.",
    Wealth: "Bintang lumbung: kuat menyimpan dan mengelola, bukan mencari secara agresif. Keuangan aman dan bertumbuh perlahan.",
    Health: "Umumnya sehat dan berdaya tahan. Keluhan biasanya di lambung dan pencernaan karena pola makan berlebih.",
    Travel: "Di luar rumah dihormati dan mudah mendapat dukungan. Perantauan aman, tidak banyak gejolak.",
    Friends: "Teman yang mapan dan sopan; hubungan awet meski tidak terlalu dalam. Anda sering jadi tempat orang menitipkan kepercayaan.",
    Career: "Cocok di manajemen, keuangan, administrasi, atau perusahaan mapan. Lebih kuat mengelola daripada merintis.",
    Property: "Salah satu letak terbaik untuk properti — mudah punya rumah dan tanah, dan betah menyimpannya.",
    Happiness: "Batin tenang, tahu cara menikmati hidup dengan aman. Tidak suka gejolak dan kejutan.",
    Parents: "Orang tua mapan dan melindungi. Atasan bersikap adil dan memberi rasa aman.",
  },
  "Tai Yin": {
    Life: "Lembut, teliti, perasa, dan berselera halus. Pandai menyimpan uang dan menjaga perasaan orang; kelemahannya mudah murung dan terlalu memendam.",
    Siblings: "Ada saudara perempuan yang menonjol atau menjadi tempat berbagi. Hubungan lembut dan saling menjaga perasaan.",
    Spouse: "Bagi pria menunjuk istri yang cantik, lembut, dan hemat; bagi wanita, pasangan yang perhatian. Hubungan mesra tetapi sensitif terhadap sikap dingin.",
    Children: "Anak perempuan menonjol, halus perasaannya, dan dekat dengan Anda. Pola asuh penuh kasih.",
    Wealth: "Bintang harta simpanan: kuat mengumpulkan diam-diam, cocok pada properti, tabungan, dan pemasukan pasif. Rezeki tumbuh perlahan tapi menetap.",
    Health: "Perhatikan ginjal, hormon, mata, dan gangguan tidur. Kondisi tubuh dipengaruhi suasana hati.",
    Travel: "Rezeki dan ketenangan banyak didapat di luar kota atau luar negeri, terutama di malam hari atau bidang yang tenang.",
    Friends: "Teman sedikit tapi dekat dan hangat, banyak dari kalangan perempuan. Anda menjaga hubungan dengan halus.",
    Career: "Cocok di bidang keuangan, properti, desain, seni, perawatan, atau apa pun yang menuntut ketelitian dan rasa.",
    Property: "Sangat baik untuk properti — mudah memiliki rumah, dan rumahnya rapi, bersih, serta nyaman.",
    Happiness: "Batin halus dan suka ketenangan. Menikmati hidup dalam sunyi; namun mudah larut dalam perasaan sendiri.",
    Parents: "Hubungan dengan ibu menonjol dan hangat. Atasan bersikap lembut dan melindungi.",
  },
  "Tan Lang": {
    Life: "Serba bisa, luwes, penuh hasrat, dan pandai bergaul. Punya banyak minat dan bakat; kelemahannya tidak fokus dan mudah tergoda kesenangan.",
    Siblings: "Saudara supel dan luas pergaulannya. Hubungan menyenangkan tetapi kepentingan sering ikut bermain.",
    Spouse: "Pasangan menarik, pandai bergaul, dan penuh daya pikat. Hubungan hidup dan penuh warna, namun perlu waspada terhadap godaan pihak ketiga.",
    Children: "Anak cerdas, pandai bergaul, dan banyak bakat. Perlu diarahkan agar tidak terlalu banyak main.",
    Wealth: "Uang datang dari pergaulan, hiburan, dan kemampuan meraih peluang. Cepat masuk, cepat keluar untuk kesenangan.",
    Health: "Perhatikan hati (liver), ginjal, dan sistem reproduksi. Sering terkait pola hidup: minuman, begadang, makan berlebih.",
    Travel: "Sangat aktif di luar, peluang datang dari perjumpaan dan jaringan. Semakin banyak bergerak semakin banyak rezeki.",
    Friends: "Lingkaran pertemanan luas dan beragam, banyak berkaitan dengan hiburan. Perlu memilah mana yang tulus.",
    Career: "Cocok di penjualan, hiburan, kuliner, seni, pemasaran, atau bidang relasi. Kurang cocok pada pekerjaan yang sunyi dan monoton.",
    Property: "Rumah dijadikan tempat bersosialisasi. Properti mudah berganti mengikuti gaya hidup.",
    Happiness: "Batin haus pengalaman dan kesenangan. Bila diarahkan ke seni atau spiritual, justru menjadi sumber ketenangan.",
    Parents: "Hubungan dengan orang tua akrab tetapi tidak terlalu terikat aturan. Atasan menyukai gaya Anda yang luwes.",
  },
  "Ju Men": {
    Life: "Analitis, kritis, teliti, dan pandai bicara. Cenderung skeptis dan sulit percaya; hidupnya kerap melewati fase salah paham sebelum diakui.",
    Siblings: "Mudah timbul salah paham dan adu argumen dengan saudara. Perlu komunikasi terbuka agar tidak berlarut.",
    Spouse: "Pasangan pandai bicara dan berpikiran tajam. Rawan perdebatan dan salah paham; sebaiknya menikah agak matang dan beda usia sedikit lebih jauh.",
    Children: "Anak banyak bicara dan berpendapat. Ada jarak pandangan antara Anda dan anak yang perlu dijembatani.",
    Wealth: "Rezeki dari mulut dan keahlian: mengajar, menjual, hukum, atau konsultasi. Sering ada persaingan dan perdebatan dalam mencari uang.",
    Health: "Perhatikan mulut, gigi, lambung, dan saluran cerna. Keluhan sering muncul saat sedang banyak pikiran.",
    Travel: "Di luar rumah mudah timbul gesekan lisan, tetapi juga di sanalah keahlian Anda diakui. Perantauan menuntut kehati-hatian bicara.",
    Friends: "Teman banyak berdebat; mudah muncul gosip atau fitnah. Pilih lingkaran yang lurus.",
    Career: "Cocok di hukum, pengajaran, media, penjualan, penyiaran, riset, atau apa pun yang mengandalkan verbal dan analisis.",
    Property: "Rumah rawan urusan sengketa, tetangga, atau perbaikan. Periksa dokumen dengan teliti.",
    Happiness: "Batin banyak menimbang dan mudah curiga. Ketenangan datang setelah belajar melepas.",
    Parents: "Ada jarak pendapat dengan orang tua atau atasan. Hubungan membaik lewat bicara jujur, bukan diam.",
  },
  "Tian Xiang": {
    Life: "Setia, tahu tata krama, suka menolong, dan pandai menjadi penengah. Kelemahannya kurang tegas dan mudah terbawa lingkungan.",
    Siblings: "Saudara saling menolong dan menjaga muka. Anda sering jadi penengah dalam keluarga.",
    Spouse: "Pasangan berpenampilan rapi, sopan, dan setia. Rumah tangga harmonis dan saling menghargai.",
    Children: "Anak sopan, tahu aturan, dan berpenampilan baik. Hubungan hangat dan saling mendukung.",
    Wealth: "Uang didapat lewat posisi pendamping, kerja sama, atau kepercayaan orang. Stabil, tidak mendadak besar.",
    Health: "Perhatikan kulit, kandung kemih, dan sistem getah bening. Umumnya kondisi sedang-sedang saja.",
    Travel: "Di luar rumah banyak yang menolong dan menaruh kepercayaan. Cocok bekerja mendampingi orang besar.",
    Friends: "Teman baik dan sopan; Anda sering menjadi tempat menitipkan urusan. Perlu berani menolak.",
    Career: "Cocok sebagai wakil, sekretaris, manajer pendamping, notaris, atau bidang layanan dan perantara.",
    Property: "Rumah rapi dan pantas. Properti sering datang dari bantuan atau kerja sama.",
    Happiness: "Batin menyukai keteraturan dan keharmonisan. Tidak tahan konflik berkepanjangan.",
    Parents: "Orang tua penyayang dan menjaga penampilan keluarga. Atasan mempercayakan banyak hal pada Anda.",
  },
  "Tian Liang": {
    Life: "Dewasa sejak muda, berprinsip, suka menasihati dan menolong. Bintang penyelamat: masalah datang, tetapi selalu ada jalan keluar. Kelemahannya sok tahu dan suka menggurui.",
    Siblings: "Ada saudara yang berperan sebagai pelindung atau penasihat. Hubungan penuh perhatian meski agak menggurui.",
    Spouse: "Pasangan lebih dewasa sifatnya atau usianya, mengayomi seperti orang tua. Hubungan aman namun kurang gairah bila terlalu berjarak usia.",
    Children: "Anak berperilaku dewasa dan tahu diri. Anda mendidik dengan nasihat dan contoh.",
    Wealth: "Rezeki dari keahlian, jabatan, atau bidang yang menolong orang. Sering ada bantuan tak terduga saat kesulitan.",
    Health: "Punya bintang penyembuh: penyakit datang tetapi ketemu obat dan dokter yang tepat. Perhatikan lambung dan payudara.",
    Travel: "Di perantauan selalu ada penolong. Cocok bekerja di bidang sosial atau kesehatan di luar kota.",
    Friends: "Teman menghormati Anda sebagai penasihat. Anda lebih banyak memberi daripada menerima.",
    Career: "Cocok di kesehatan, hukum, pendidikan, pengawasan, agama, atau lembaga sosial. Kuat pada peran yang mengawasi dan menolong.",
    Property: "Properti sering berkaitan dengan warisan atau pemberian orang tua. Rumah dipakai untuk merawat keluarga.",
    Happiness: "Batin tenang dan cenderung religius atau filosofis. Ini salah satu letak terbaik Tian Liang.",
    Parents: "Orang tua berperan besar melindungi Anda. Atasan bersikap seperti pembimbing.",
  },
  "Qi Sha": {
    Life: "Tegas, berani, mandiri, dan tahan banting. Hidup penuh perjuangan dan perubahan besar; kelemahannya keras kepala dan terlalu cepat mengambil keputusan.",
    Siblings: "Saudara berwatak keras dan mandiri, mudah bersitegang. Masing-masing berjalan sendiri.",
    Spouse: "Pasangan tegas dan berkemauan kuat. Hubungan mudah panas bila keduanya tidak mau mengalah; jangan menikah terlalu muda.",
    Children: "Anak berkemauan keras dan sulit diatur. Pendekatan lembut lebih berhasil daripada tekanan.",
    Wealth: "Uang diperoleh dengan berjuang dan berani ambil risiko. Naik-turun tajam; cocok pada usaha yang menuntut keberanian.",
    Health: "Rawan cedera, kecelakaan, atau tindakan operasi. Perhatikan paru-paru dan cedera otot-tulang.",
    Travel: "Kuat di luar rumah — perantauan justru membuka jalan. Banyak bergerak dan berpindah medan.",
    Friends: "Teman berkarakter keras; mudah setia tetapi juga mudah berpisah. Hubungan diuji kepentingan.",
    Career: "Cocok di militer, keamanan, konstruksi, olahraga, mesin, atau wirausaha berisiko. Kurang cocok pada pekerjaan administratif.",
    Property: "Properti diperoleh dengan usaha keras dan sering berganti. Ada kemungkinan renovasi atau bongkar besar.",
    Happiness: "Batin tidak bisa diam, selalu ingin bergerak dan berjuang. Ketenangan datang setelah lelah.",
    Parents: "Hubungan dengan orang tua tegas dan agak berjarak. Atasan keras namun menghargai keberanian Anda.",
  },
  "Po Jun": {
    Life: "Berani mendobrak, tidak takut memulai dari nol, dan menolak aturan lama. Hidup banyak perubahan besar; kelemahannya impulsif dan boros tenaga.",
    Siblings: "Hubungan dengan saudara mudah berubah dan renggang. Sering terpisah jarak atau jalan hidup.",
    Spouse: "Pasangan berwatak kuat dan penuh dinamika. Hubungan mudah bergolak; menikah terlambat lebih aman.",
    Children: "Anak aktif, berani, dan sulit dikekang. Perlu ruang bereksplorasi.",
    Wealth: "Uang datang dan pergi dengan cepat, sering lewat perombakan atau usaha baru. Cocok pada bidang yang membangun ulang sesuatu.",
    Health: "Rawan luka, operasi, dan masalah gigi atau reproduksi. Perlu menjaga stamina.",
    Travel: "Perantauan membawa perubahan besar dan peluang baru. Banyak berpindah tempat dan bidang.",
    Friends: "Teman datang dan pergi; jarang lingkaran yang bertahan lama. Mudah kena imbas urusan orang lain.",
    Career: "Cocok di bidang yang membongkar dan membangun: konstruksi, perintisan usaha, transformasi perusahaan, teknik, laut, atau militer.",
    Property: "Sering pindah rumah, renovasi, atau membeli properti lama untuk diperbaiki.",
    Happiness: "Batin gelisah dan cepat bosan pada kemapanan. Puas saat sedang membangun sesuatu.",
    Parents: "Hubungan dengan orang tua bergejolak atau berjarak. Anda cenderung mandiri sejak awal.",
  },

  // ── 16 Bintang Bantu (Aux) ──────────────────────────────────────────────
  "Wen Chang": {
    Life: "Menambah kecerdasan formal, ketelitian tulisan, dan penampilan terpelajar. Membuat orangnya rapi berpikir dan pandai menyusun kata.",
    Siblings: "Ada saudara yang berpendidikan baik atau menonjol secara akademik; hubungan terjalin lewat diskusi.",
    Spouse: "Pasangan terpelajar, rapi, dan berselera baik. Perjodohan sering bermula dari lingkungan sekolah atau kerja.",
    Children: "Anak berbakat akademik dan mudah berprestasi di sekolah.",
    Wealth: "Uang dari keahlian tulis, ilmu, kontrak, atau profesi terpelajar. Perhatikan detail dokumen.",
    Health: "Umumnya meringankan; keluhan lebih ke saraf dan kelelahan pikiran.",
    Travel: "Di luar rumah dikenal sebagai orang berilmu; peluang datang lewat pendidikan atau sertifikasi.",
    Friends: "Lingkaran teman berpendidikan dan sopan; saling bantu lewat informasi.",
    Career: "Sangat baik untuk jalur akademik, penulisan, hukum, administrasi, dan ujian atau seleksi resmi.",
    Property: "Rumah rapi dan berisi buku; urusan surat properti berjalan lancar.",
    Happiness: "Batin menikmati belajar, membaca, dan hal-hal yang tertata.",
    Parents: "Orang tua berpendidikan atau menghargai pendidikan; atasan menghargai kerapian kerja Anda.",
  },
  "Wen Qu": {
    Life: "Menambah bakat seni, kefasihan bicara, dan daya pikat pribadi. Lebih ke kecerdasan rasa dan ekspresi daripada akademik formal.",
    Siblings: "Saudara berbakat seni atau pandai bicara; hubungan cair dan menyenangkan.",
    Spouse: "Pasangan menarik, romantis, dan pandai berkata-kata. Perlu waspada terhadap godaan bila bertemu bintang asmara lain.",
    Children: "Anak berbakat seni, musik, atau berbicara di depan umum.",
    Wealth: "Rezeki dari seni, komunikasi, penampilan, atau keterampilan bicara.",
    Health: "Ringan; keluhan lebih terkait emosi dan gangguan tidur.",
    Travel: "Mudah disukai orang di luar rumah; peluang lewat pergaulan dan penampilan.",
    Friends: "Teman-teman menyenangkan dan berbakat; suasana pergaulan hangat.",
    Career: "Cocok di seni, musik, media, humas, pemasaran, dan bidang yang menjual komunikasi.",
    Property: "Rumah dihias indah dan bernuansa artistik.",
    Happiness: "Batin menikmati keindahan, musik, dan hal-hal romantis.",
    Parents: "Hubungan dengan orang tua hangat dan penuh bicara; atasan menyukai gaya Anda.",
  },
  "Zuo Fu": {
    Life: "Menambah wibawa lembut dan banyak pertolongan orang. Orangnya loyal, suka membantu, dan mudah dipercaya.",
    Siblings: "Saudara menjadi penolong nyata; hubungan saling menopang.",
    Spouse: "Pasangan suportif dan setia. Namun bila berdiri sendiri tanpa You Bi, kadang menandakan ada pihak ketiga yang ikut campur.",
    Children: "Anak penurut dan membantu; jumlah anak cenderung lebih banyak.",
    Wealth: "Ada bantuan orang dalam urusan uang; rezeki bertambah lewat kerja sama.",
    Health: "Meringankan penyakit; selalu ada yang merawat saat sakit.",
    Travel: "Di perantauan banyak penolong dan pendukung.",
    Friends: "Bawahan dan teman setia serta membantu; ini letak yang sangat baik.",
    Career: "Karier terbantu oleh atasan dan rekan; cocok sebagai tangan kanan atau pemimpin yang didukung tim.",
    Property: "Mendapat bantuan dalam memperoleh rumah atau properti.",
    Happiness: "Batin tenang karena merasa didukung; senang menolong orang.",
    Parents: "Orang tua dan atasan bersikap melindungi dan membantu.",
  },
  "You Bi": {
    Life: "Serupa Zuo Fu: menambah pertolongan dan keluwesan bergaul, dengan sifat lebih halus dan mengalir.",
    Siblings: "Saudara membantu di belakang layar; hubungan halus dan saling menjaga.",
    Spouse: "Pasangan pengertian dan suka membantu. Sama seperti Zuo Fu, bila berdiri sendiri perlu waspada campur tangan pihak lain.",
    Children: "Anak berhati lembut dan suka menolong.",
    Wealth: "Rezeki bertambah lewat relasi dan bantuan tak terduga.",
    Health: "Meringankan keluhan; pemulihan lebih cepat karena ada yang mendampingi.",
    Travel: "Selalu ada yang menolong saat di luar kota atau luar negeri.",
    Friends: "Lingkaran pertemanan luas dan suportif.",
    Career: "Cocok di posisi pendamping, koordinasi, atau kerja tim; karier lancar berkat dukungan.",
    Property: "Bantuan orang memudahkan urusan rumah dan properti.",
    Happiness: "Batin damai dan merasa dicukupi lewat hubungan baik.",
    Parents: "Orang tua penyayang; atasan bersikap mengayomi.",
  },
  "Lu Cun": {
    Life: "Bintang rezeki dan kecukupan. Orangnya hemat, hati-hati, mandiri secara materi, tetapi cenderung penyendiri dan enggan berbagi.",
    Siblings: "Saudara mapan tetapi masing-masing menjaga urusannya sendiri.",
    Spouse: "Pasangan hemat dan bertanggung jawab soal uang; rumah tangga aman secara materi.",
    Children: "Anak hemat dan tahu nilai uang; jumlahnya cenderung sedikit.",
    Wealth: "Letak terbaiknya — rezeki lancar, stabil, dan mudah menabung. Uang bertahan, bukan lewat begitu saja.",
    Health: "Menambah daya tahan; keluhan biasanya di lambung karena pola makan.",
    Travel: "Rezeki mudah didapat di luar kota; perantauan menguntungkan.",
    Friends: "Teman sedikit tapi berkaitan dengan rezeki; hubungan berbasis kepentingan yang sehat.",
    Career: "Pekerjaan memberi penghasilan tetap dan aman; cocok di keuangan atau posisi bergaji stabil.",
    Property: "Baik untuk properti — mudah memiliki dan menyimpan aset tak bergerak.",
    Happiness: "Batin tenang karena merasa cukup; namun bisa terlalu perhitungan.",
    Parents: "Orang tua memberi dukungan materi; atasan menghargai dengan imbalan nyata.",
  },
  "Qing Yang": {
    Life: "Tajam, cepat, berani, tetapi tidak sabar dan mudah tersulut. Menambah ketegasan sekaligus risiko luka dan konflik.",
    Siblings: "Mudah bersitegang dengan saudara; perlu menjaga ucapan.",
    Spouse: "Hubungan tajam dan mudah panas; perlu jeda saat berselisih.",
    Children: "Anak keras dan mudah terluka saat kecil; awasi keselamatannya.",
    Wealth: "Uang didapat dengan bersaing; rawan sengketa atau kehilangan mendadak.",
    Health: "Rawan luka, benda tajam, kecelakaan, dan tindakan operasi.",
    Travel: "Perlu hati-hati di jalan dan dalam pergaulan di luar; risiko gesekan lebih besar.",
    Friends: "Mudah timbul perselisihan dengan teman atau bawahan.",
    Career: "Cocok di bidang yang butuh ketajaman: bedah, teknik, keamanan, militer, atau olahraga.",
    Property: "Rawan urusan sengketa atau kerusakan pada rumah.",
    Happiness: "Batin mudah gelisah dan tidak sabar; perlu latihan menenangkan diri.",
    Parents: "Hubungan dengan orang tua atau atasan mudah bergesekan.",
  },
  "Tuo Luo": {
    Life: "Menambah ketekunan tetapi juga sifat menunda, memendam, dan berputar-putar. Masalah tidak meledak, melainkan berlarut.",
    Siblings: "Ganjalan lama dengan saudara yang tidak dibicarakan.",
    Spouse: "Hubungan tersendat dan penuh salah paham yang dipendam; perlu keterbukaan.",
    Children: "Urusan anak sering tertunda atau berjalan lambat.",
    Wealth: "Uang datang terlambat atau tersendat; sering ada piutang yang macet.",
    Health: "Keluhan kronis dan lama sembuh; perhatikan tulang, gigi, dan persendian.",
    Travel: "Perjalanan sering tertunda atau berputar; urusan di luar bertele-tele.",
    Friends: "Ada teman yang menghambat diam-diam; kepercayaan perlu diuji.",
    Career: "Karier naik lambat, tetapi tahan banting. Cocok di pekerjaan yang menuntut ketekunan panjang.",
    Property: "Urusan properti berlarut: surat, renovasi, atau serah terima tertunda.",
    Happiness: "Batin menyimpan beban lama; perlu belajar melepaskan.",
    Parents: "Hubungan dengan orang tua atau atasan terasa mengganjal namun tidak terucap.",
  },
  "Tian Kui": {
    Life: "Bintang penolong siang. Menandakan adanya orang berkedudukan yang membantu, dan pribadi yang berwibawa serta terpandang.",
    Siblings: "Ada saudara yang menjadi penolong berpengaruh.",
    Spouse: "Pasangan terpandang atau membawa keberuntungan; sering dikenalkan oleh orang lain.",
    Children: "Anak mendapat banyak dukungan dari orang berkedudukan.",
    Wealth: "Rezeki datang lewat bantuan orang penting atau kesempatan yang dibukakan.",
    Health: "Saat sakit mudah bertemu dokter yang tepat.",
    Travel: "Di perantauan selalu ada orang berkedudukan yang menolong.",
    Friends: "Teman-teman berkualitas dan berpengaruh.",
    Career: "Karier terangkat berkat atasan atau mentor; peluang promosi baik.",
    Property: "Urusan properti dimudahkan oleh koneksi.",
    Happiness: "Batin merasa dilindungi dan beruntung.",
    Parents: "Orang tua atau atasan berperan sebagai penolong utama hidup Anda.",
  },
  "Tian Yue": {
    Life: "Bintang penolong malam. Bantuan datang secara halus dan tidak menonjol; pribadinya lembut, disukai, dan sering ditolong tanpa diminta.",
    Siblings: "Ada saudara yang membantu diam-diam.",
    Spouse: "Pasangan membawa keberuntungan dan bersikap lembut; perjodohan lewat perantara.",
    Children: "Anak beruntung dan mudah mendapat pertolongan orang.",
    Wealth: "Rezeki halus dari bantuan orang, sering datang di saat terdesak.",
    Health: "Pertolongan medis datang tepat waktu; pemulihan dimudahkan.",
    Travel: "Ada penolong tak terduga saat di luar rumah, terutama pada situasi sulit.",
    Friends: "Teman yang tulus membantu tanpa banyak bicara.",
    Career: "Ada tangan tersembunyi yang mendukung karier; promosi datang tanpa banyak berjuang.",
    Property: "Urusan rumah dimudahkan oleh bantuan keluarga atau kerabat.",
    Happiness: "Batin tenang dan merasa dijaga.",
    Parents: "Orang tua, terutama sosok perempuan, menjadi penolong penting.",
  },
  "Huo Xing": {
    Life: "Menambah semangat meledak, keberanian, dan sifat tidak sabaran. Naik cepat, marah cepat, reda pun cepat.",
    Siblings: "Perselisihan dengan saudara datang tiba-tiba tetapi cepat mereda.",
    Spouse: "Hubungan panas dan mudah meledak; perlu belajar menahan reaksi pertama.",
    Children: "Anak aktif, cepat panas, dan mudah cedera karena gegabah.",
    Wealth: "Uang datang mendadak dan pergi mendadak; bersama Tan Lang justru menandakan rezeki kejutan yang besar.",
    Health: "Rawan demam, radang, luka bakar, dan masalah kulit.",
    Travel: "Perjalanan sering mendadak; hati-hati di jalan dan dengan api atau listrik.",
    Friends: "Konflik dengan teman meletup tiba-tiba.",
    Career: "Cocok di bidang bertempo cepat: api, mesin, teknologi, militer, olahraga, atau tekanan tinggi.",
    Property: "Perhatikan risiko kebakaran dan korsleting di rumah.",
    Happiness: "Batin mudah tersulut dan sulit tenang; olahraga membantu menyalurkan.",
    Parents: "Hubungan dengan orang tua atau atasan mudah panas sesaat.",
  },
  "Ling Xing": {
    Life: "Serupa Huo Xing tetapi lebih dingin dan memendam. Marahnya tidak meledak melainkan mengendap dan bertahan lama.",
    Siblings: "Ganjalan dengan saudara yang dipendam dalam waktu lama.",
    Spouse: "Ketegangan dalam hubungan bersifat diam dan berlarut; sikap dingin lebih merusak daripada pertengkaran.",
    Children: "Anak pendiam tetapi keras kepala di dalam.",
    Wealth: "Rezeki naik-turun secara tersembunyi; ada kebocoran yang tidak disadari.",
    Health: "Keluhan tersembunyi dan kronis; perhatikan saraf dan gangguan tidur.",
    Travel: "Ada hambatan tak terlihat di luar rumah; perlu waspada tanpa panik.",
    Friends: "Ada teman yang menyimpan rasa tidak suka diam-diam.",
    Career: "Cocok di pekerjaan teknis, riset, atau yang menuntut ketahanan diam-diam.",
    Property: "Masalah rumah bersifat tersembunyi: rembes, listrik, atau struktur.",
    Happiness: "Batin menyimpan gelisah yang tidak diungkapkan.",
    Parents: "Hubungan dengan orang tua terasa dingin meski tidak ada konflik terbuka.",
  },
  "Di Kong": {
    Life: "Membuat pikiran melompat di luar kebiasaan, idealis, dan tidak terikat materi. Cocok untuk pemikir dan pencari makna, kurang cocok untuk pengumpul harta.",
    Siblings: "Hubungan dengan saudara terasa hampa atau jauh.",
    Spouse: "Hubungan terasa kurang berpijak; harapan sering tidak sesuai kenyataan.",
    Children: "Urusan anak tidak sesuai rencana; jumlah anak cenderung sedikit.",
    Wealth: "Rezeki mudah bocor dan rencana keuangan sering meleset. Hindari spekulasi dan pinjam-meminjam.",
    Health: "Keluhan yang sulit dijelaskan sebabnya; perhatikan pernapasan dan saraf.",
    Travel: "Rencana perjalanan sering batal atau berubah; hasil di luar tidak sesuai harapan.",
    Friends: "Teman datang dan pergi tanpa jejak; bantuan sering tidak jadi.",
    Career: "Cocok di bidang kreatif, riset, spiritual, atau filsafat. Kurang cocok di bidang dagang murni.",
    Property: "Urusan properti mudah gagal di tengah jalan; periksa sebelum memutuskan.",
    Happiness: "Batin cenderung filosofis dan tidak terikat duniawi; ini letak terbaiknya.",
    Parents: "Hubungan dengan orang tua terasa berjarak secara batin.",
  },
  "Di Jie": {
    Life: "Menambah keberanian mengambil jalan tidak lazim, tetapi juga kerugian mendadak dan perubahan tak terduga.",
    Siblings: "Saudara bisa membawa beban atau kerugian tak terduga.",
    Spouse: "Hubungan mudah terganggu peristiwa mendadak dari luar.",
    Children: "Perlu perhatian ekstra pada keselamatan anak.",
    Wealth: "Rawan kehilangan uang mendadak: tertipu, terjebak, atau salah investasi. Jangan menjamin utang orang.",
    Health: "Rawan kejadian mendadak dan kecelakaan; jaga kewaspadaan.",
    Travel: "Perlu hati-hati di perjalanan; risiko kehilangan barang atau musibah kecil.",
    Friends: "Ada teman yang membawa kerugian; hati-hati dalam kerja sama uang.",
    Career: "Karier berjalan berliku dengan kejutan; cocok pada bidang yang tidak konvensional.",
    Property: "Rawan kerugian dalam transaksi properti; periksa dokumen dengan sangat teliti.",
    Happiness: "Batin gelisah karena rasa tidak aman; belajar berserah membantu.",
    Parents: "Beban keluarga bisa datang mendadak dari sisi orang tua.",
  },
  "Hong Luan": {
    Life: "Menambah daya tarik, wajah menyenangkan, dan rezeki asmara. Orangnya hangat dan mudah disukai lawan jenis.",
    Siblings: "Hubungan dengan saudara hangat dan penuh kasih.",
    Spouse: "Bintang asmara utama — menandakan pernikahan atau perjumpaan jodoh, terutama saat dilewati Da Xian atau Liu Nian.",
    Children: "Menandakan kabar kehamilan atau kelahiran saat dilewati tahun berjalan.",
    Wealth: "Rezeki lewat hubungan baik, penampilan, atau bidang yang menyenangkan orang.",
    Health: "Perhatikan sistem reproduksi dan hormon.",
    Travel: "Mudah bertemu jodoh atau relasi baik saat di luar rumah.",
    Friends: "Pergaulan hangat dan banyak teman lawan jenis.",
    Career: "Cocok di bidang keindahan, pernikahan, hiburan, dan layanan pelanggan.",
    Property: "Rumah bernuansa hangat; sering ada acara keluarga di dalamnya.",
    Happiness: "Batin romantis dan menyukai keindahan hubungan.",
    Parents: "Hubungan dengan orang tua akrab dan penuh kasih sayang.",
  },
  "Tian Xi": {
    Life: "Menambah keceriaan, wajah awet muda, dan suasana gembira. Pasangan alami Hong Luan.",
    Siblings: "Suasana kekeluargaan gembira; banyak kabar baik dari saudara.",
    Spouse: "Menandakan kegembiraan dalam pernikahan; sering muncul saat tahun jodoh atau kelahiran anak.",
    Children: "Kuat menandakan kelahiran anak; hubungan dengan anak penuh tawa.",
    Wealth: "Rezeki datang bersama kabar gembira atau perayaan.",
    Health: "Umumnya baik; pemulihan cepat karena suasana hati positif.",
    Travel: "Perjalanan menyenangkan dan membawa kabar baik.",
    Friends: "Lingkaran teman ceria dan menyenangkan.",
    Career: "Cocok di bidang perayaan, acara, hiburan, dan anak-anak.",
    Property: "Rumah ramai dan menjadi tempat acara gembira.",
    Happiness: "Batin ringan dan mudah gembira; letak yang sangat baik.",
    Parents: "Hubungan dengan orang tua penuh suasana gembira.",
  },
  "Tian Ma": {
    Life: "Menambah kegesitan, semangat bergerak, dan sifat tidak betah diam. Hidupnya banyak berpindah dan bepergian.",
    Siblings: "Saudara sering merantau atau tinggal berjauhan.",
    Spouse: "Pasangan sibuk bergerak atau sering bepergian; hubungan jarak jauh mungkin terjadi.",
    Children: "Anak aktif dan kelak cenderung merantau.",
    Wealth: "Rezeki dari bergerak: dagang, perjalanan, logistik, atau luar kota. Bersama Lu Cun menjadi Lu Ma Jiao Chi — pertanda rezeki lancar yang sangat baik.",
    Health: "Perhatikan kaki dan risiko cedera saat bepergian.",
    Travel: "Letak terkuatnya — banyak perjalanan, dan keberuntungan memang ada di luar rumah.",
    Friends: "Teman tersebar di banyak tempat; relasi lintas kota.",
    Career: "Cocok di transportasi, perdagangan, ekspor-impor, pariwisata, atau pekerjaan lapangan.",
    Property: "Sering pindah rumah; properti bisa berada di kota lain.",
    Happiness: "Batin gelisah bila terlalu lama diam; menikmati perjalanan.",
    Parents: "Sering berjauhan dengan orang tua karena urusan pekerjaan atau perantauan.",
  },
};
